import { Theme } from "@shared/types/theme";

export const defaultTheme: Theme = {
  name: "Carbon",
  description: `Carbon theme for SnipPad`,
  author: "calebephrem",
  theme: {
    type: "dark",
    client: {
      backgroundPrimary: "#0d0d0f",
      backgroundSecondary: "#161618",
      backgroundTertiary: "#1e1e22",
      overlayColor: "#222226",
      borderColor: "#2a2a30",
      borderColorSubtle: "#1f1f24",
      textPrimary: "#e8e8ec",
      textSecondary: "#a0a0a8",
      textMuted: "#6b6b73",
      accentColor: "#e0a56a",
      accentColorHover: "#e8b580",
      accentColorMuted: "rgba(224, 168, 112, 0.5)",
      danger: "#d06060",
      dangerHover: "#f08585",
      success: "#7ec699",
      warning: "#e8c878",
      inputBackground: "rgba(224, 168, 112, 0.12)",
      scrollbarThumb: "#3a3a42",
      scrollbarTrack: "transparent",
      shadow: "0 8px 32px rgba(0, 0, 0, 0.4)",
    },
    editor: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", foreground: "e8e8ec", background: "161618" },
        { token: "comment", foreground: "6b6b73", fontStyle: "italic" },
        { token: "keyword", foreground: "e0a870", fontStyle: "bold" },
        { token: "keyword.control", foreground: "e0a870" },
        { token: "operator", foreground: "e8b580" },
        { token: "string", foreground: "7ec699" },
        { token: "string.escape", foreground: "e8c878" },
        { token: "number", foreground: "e8c878" },
        { token: "regexp", foreground: "e57373" },
        { token: "type", foreground: "82aaff" },
        { token: "type.identifier", foreground: "82aaff" },
        { token: "class", foreground: "82aaff" },
        { token: "function", foreground: "c792ea" },
        { token: "function.call", foreground: "c792ea" },
        { token: "variable", foreground: "e8e8ec" },
        { token: "variable.parameter", foreground: "f78c6c" },
        { token: "variable.predefined", foreground: "e0a870" },
        { token: "constant", foreground: "f78c6c" },
        { token: "delimiter", foreground: "a0a0a8" },
        { token: "tag", foreground: "e0a870" },
        { token: "attribute.name", foreground: "c792ea" },
        { token: "attribute.value", foreground: "7ec699" },
        { token: "json.key", foreground: "e0a870" },
      ],
      colors: {
        "editor.background": "#161618",
        "editor.foreground": "#e8e8ec",
        "editorCursor.foreground": "#e0a870",
        "editor.lineHighlightBackground": "#1e1e2280",
        "editor.selectionBackground": "#2a2a30",
        "editor.inactiveSelectionBackground": "#1e1e22",
        "editorLineNumber.foreground": "#6b6b73",
        "editorLineNumber.activeForeground": "#a0a0a8",
        "editorGutter.background": "#161618",
        "editorBracketMatch.background": "#2a2a3080",
        "editorBracketMatch.border": "#e0a870",
        "editorSuggestWidget.background": "#1e1e22",
        "editorSuggestWidget.border": "#2a2a30",
        "editorSuggestWidget.foreground": "#e8e8ec",
        "editorSuggestWidget.selectedBackground": "#2a2a30",
        "editorSuggestWidget.highlightForeground": "#e0a870",
        "editorWidget.background": "#1e1e22",
        "editorWidget.border": "#2a2a30",
        "scrollbarSlider.background": "#3a3a4280",
        "scrollbarSlider.hoverBackground": "#3a3a42cc",
        "scrollbarSlider.activeBackground": "#e0a87080",
      },
    },
  },
};
