import pkg from "../../../package.json" with { type: "json" };
import { Theme } from "../types/theme";

export const defaultTheme: Theme = {
  name: "Carbon",
  description: `Carbon theme for ${pkg.name}`,
  author: "calebephrem",
  theme: {
    client: {
      backgroundPrimary: "#0d0d0f",
      backgroundSecondary: "#161618",
      backgroundTertiary: "#1e1e22",
      backgroundElevated: "#222226",
      overlayColor: "rgba(0, 0, 0, 0.55)",
      borderColor: "#2a2a30",
      borderColorSubtle: "#1f1f24",
      textPrimary: "#e8e8ec",
      textSecondary: "#a0a0a8",
      textMuted: "#6b6b73",
      accentColor: "#e0a870",
      accentColorHover: "#e8b580",
      accentColorMuted: "rgba(224, 168, 112, 0.15)",
      danger: "#e57373",
      dangerHover: "#f08585",
      success: "#7ec699",
      warning: "#e8c878",
      tagBackground: "rgba(224, 168, 112, 0.12)",
      tagText: "#e0a870",
      scrollbarThumb: "#3a3a42",
      scrollbarTrack: "transparent",
      editorBackground: "#161618",
      shadow: "0 8px 32px rgba(0, 0, 0, 0.4)",
    },
    editor: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "comment", foreground: "6b6b73", fontStyle: "italic" },
        { token: "keyword", foreground: "e0a870" },
        { token: "string", foreground: "7ec699" },
        { token: "number", foreground: "e8c878" },
        { token: "type", foreground: "a0a0a8" },
        { token: "function", foreground: "b0c8e0" },
        { token: "variable", foreground: "e8e8ec" },
        { token: "constant", foreground: "e8c878" },
        { token: "operator", foreground: "c0c0c8" },
        { token: "delimiter", foreground: "a0a0a8" },
        { token: "tag", foreground: "e57373" },
        { token: "attribute.name", foreground: "e0a870" },
        { token: "attribute.value", foreground: "7ec699" },
        { token: "regexp", foreground: "e8c878" },
      ],
      colors: {
        "editor.background": "#161618",
        "editor.foreground": "#e8e8ec",
        "editorLineNumber.foreground": "#6b6b73",
        "editorLineNumber.activeForeground": "#a0a0a8",
        "editor.selectionBackground": "#2a2a30",
        "editor.inactiveSelectionBackground": "#1e1e22",
        "editorCursor.foreground": "#e0a870",
        "editorWhitespace.foreground": "#2a2a30",
        "editorIndentGuide.background": "#1e1e22",
        "editorIndentGuide.activeBackground": "#2a2a30",
        "editorBracketMatch.background": "#2a2a3080",
        "editorBracketMatch.border": "#e0a870",
        "editorGutter.background": "#161618",
        "editorWidget.background": "#1e1e22",
        "editorWidget.border": "#2a2a30",
        "editorHoverWidget.background": "#1e1e22",
        "editorHoverWidget.border": "#2a2a30",
        "editorHoverWidget.foreground": "#e8e8ec",
        "editorSuggestWidget.background": "#1e1e22",
        "editorSuggestWidget.border": "#2a2a30",
        "editorSuggestWidget.selectedBackground": "#2a2a30",
        "minimap.background": "#111113",
        "scrollbarSlider.background": "#2a2a3080",
        "scrollbarSlider.hoverBackground": "#2a2a30b0",
        "editorError.foreground": "#e57373",
        "editorWarning.foreground": "#e8c878",
        "editorInfo.foreground": "#b0c8e0",
        "editorLink.activeForeground": "#e0a870",
      },
    },
  },
};
