export const langMap: Record<string, string[]> = {
  abap: ["abap"],
  apex: ["apex"],
  bat: ["bat", "cmd"],
  bicep: ["bicep"],
  c: ["c", "cats", "idc", "w"],
  clojure: [
    "boot",
    "cl2",
    "clj",
    "cljc",
    "cljs",
    "cljs.hl",
    "cljscm",
    "cljx",
    "hic",
  ],
  coffeescript: ["_coffee", "cake", "cjsx", "coffee", "cson", "iced"],
  cpp: [
    "c++",
    "cc",
    "cp",
    "cpp",
    "cxx",
    "h",
    "h++",
    "hh",
    "hpp",
    "hxx",
    "inl",
    "ipp",
    "tcc",
    "tpp",
  ],
  csharp: ["cs", "csx"],
  css: ["css"],
  cypher: ["cyp", "cypher"],
  dart: ["dart"],
  dockerfile: ["dockerfile"],
  ecl: ["ecl", "eclxml"],
  elixir: ["ex", "exs"],
  freemarker2: ["ftl"],
  fsharp: ["fs", "fsi", "fsscript", "fsx"],
  go: ["go"],
  graphql: ["gql", "graphql"],
  handlebars: ["handlebars", "hbs", "mustache"],
  hcl: ["hcl", "tf"],
  html: ["htm", "html", "html.hl", "xht", "xhtml"],
  ini: ["cfg", "ini", "prefs", "pro", "properties"],
  java: ["jav", "java"],
  javascript: [
    "_js",
    "bones",
    "cjs",
    "es",
    "es6",
    "gs",
    "jake",
    "js",
    "jsb",
    "jscad",
    "jsfl",
    "jsm",
    "jss",
    "jsx",
    "mjs",
    "njs",
    "pac",
    "sjs",
    "ssjs",
    "sublime-build",
    "sublime-commands",
    "sublime-completions",
    "sublime-keymap",
    "sublime-macro",
    "sublime-menu",
    "sublime-mousemap",
    "sublime-project",
    "sublime-settings",
    "sublime-theme",
    "sublime-workspace",
    "sublime_metrics",
    "sublime_session",
    "xsjs",
    "xsjslib",
  ],
  json: [
    "geojson",
    "json",
    "json5",
    "jsonc",
    "lock",
    "topojson",
    "webmanifest",
  ],
  julia: ["jl"],
  kotlin: ["kt", "ktm", "kts"],
  less: ["less"],
  liquid: ["liquid"],
  lua: ["lua", "nse", "pd_lua", "rbxs", "wlua"],
  markdown: ["markdown", "md", "mdx", "mkd", "mkdn", "mkdown"],
  "objective-c": ["m"],
  pascal: ["dfm", "dpr", "lpr", "pas", "pp"],
  perl: ["al", "perl", "ph", "pl", "plx", "pm", "pod", "psgi", "t"],
  php: ["aw", "ctp", "php", "php3", "php4", "php5", "phps", "phpt"],
  powerquery: ["pq"],
  powershell: ["ps1", "psd1", "psm1"],
  protobuf: ["proto"],
  pug: ["jade", "pug"],
  python: [
    "bzl",
    "gyp",
    "j2",
    "lmi",
    "py",
    "pyde",
    "pyp",
    "pyt",
    "pyw",
    "rpy",
    "tac",
    "wsgi",
    "xpy",
  ],
  qsharp: ["qs"],
  r: ["r", "rd", "rsx"],
  razor: ["cshtml", "razor"],
  restructuredtext: ["rest", "rest.txt", "rst", "rst.txt"],
  ruby: [
    "builder",
    "gemspec",
    "god",
    "irbrc",
    "jbuilder",
    "mspec",
    "podspec",
    "rabl",
    "rake",
    "rb",
    "rbuild",
    "rbw",
    "rbx",
    "ru",
    "ruby",
    "thor",
    "watchr",
  ],
  rust: ["rs", "rs.in"],
  sb: ["sb"],
  scala: ["sbt", "sc", "scala"],
  scheme: ["scm", "sld", "sls", "sps", "ss"],
  scss: ["scss"],
  shell: [
    "bash",
    "bats",
    "cgi",
    "command",
    "fcgi",
    "ksh",
    "sh",
    "sh.in",
    "tmux",
    "tool",
    "zsh",
  ],
  sol: ["sol"],
  sparql: ["rq", "sparql"],
  sql: ["cql", "ddl", "inc", "prc", "sql", "tab", "udf", "viw"],
  st: ["st"],
  swift: ["swift"],
  systemverilog: ["sv", "svh", "systemverilog", "v", "veo", "vh"],
  tcl: ["adp", "tcl", "tm"],
  twig: ["jinja", "jinja2", "twig"],
  typescript: ["cts", "mts", "ts", "tsx"],
  typespec: ["tsp"],
  vb: ["vb"],
  wgsl: ["wgsl"],
  xml: [
    "ant",
    "axml",
    "ccxml",
    "clixml",
    "cproject",
    "csl",
    "csproj",
    "ct",
    "dita",
    "ditamap",
    "ditaval",
    "dll.config",
    "dotsettings",
    "filters",
    "fsproj",
    "fxml",
    "glade",
    "gml",
    "grxml",
    "iml",
    "ivy",
    "jelly",
    "jsproj",
    "kml",
    "launch",
    "mdpolicy",
    "mm",
    "mod",
    "mxml",
    "nproj",
    "nuspec",
    "odd",
    "osm",
    "plist",
    "pluginspec",
    "props",
    "ps1xml",
    "psc1",
    "pt",
    "rdf",
    "rss",
    "scxml",
    "srdf",
    "storyboard",
    "sttheme",
    "sublime-snippet",
    "targets",
    "tmcommand",
    "tml",
    "tmlanguage",
    "tmpreferences",
    "tmsnippet",
    "tmtheme",
    "ui",
    "urdf",
    "ux",
    "vbproj",
    "vcxproj",
    "vssettings",
    "vxml",
    "wsdl",
    "wsf",
    "wxi",
    "wxl",
    "wxs",
    "x3d",
    "xacro",
    "xaml",
    "xib",
    "xlf",
    "xliff",
    "xmi",
    "xml",
    "xml.dist",
    "xproj",
    "xsd",
    "xul",
    "zcml",
  ],
  yaml: [
    "reek",
    "rviz",
    "sublime-syntax",
    "syntax",
    "yaml",
    "yaml-tmlanguage",
    "yml",
  ],
  plaintext: ["txt"],
};

export function getLangFromExt(
  filenameOrExt: string | undefined,
): string | undefined {
  if (!filenameOrExt) return;
  const clean = filenameOrExt.trim().toLowerCase();
  const ext = clean.includes(".") ? (clean.split(".").pop() ?? "") : clean;

  for (const [lang, extensions] of Object.entries(langMap)) {
    if (extensions.includes(ext)) {
      return lang;
    }
  }

  return undefined;
}
